# Generated by go2rpm 1.8.2
%bcond_without check
%bcond_without bootstrap

# https://github.com/google/go-attestation
%global goipath         github.com/google/go-attestation
Version:                0.4.3

%gometa -f

%global common_description %{expand:
Go-Attestation abstracts remote attestation operations across a variety of
platforms and TPMs, enabling remote validation of machine identity and state.}

%global golicenses      LICENSE
%global godocs          docs CONTRIBUTING.md README.md attest/attest-\\\
                        tool/README.md

Name:           %{goname}
Release:        %autorelease
Summary:        None

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

BuildRequires: golang(github.com/google/certificate-transparency-go/x509)
BuildRequires: golang-github-google-tspi-devel
BuildRequires: golang-github-google-tpm-devel

%description %{common_description}

%gopkg

%prep
%goprep

%build
for cmd in ci attest/attest-tool; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CONTRIBUTING.md README.md attest/attest-tool/README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
