# Generated by go2rpm 1.8.2
%bcond_without check
%bcond_without bootstrap
%if %{with bootstrap}
%global debug_package %{nil}
%endif

# https://github.com/google/go-attestation
%global goipath         github.com/google/go-attestation
Version:                0.4.4
%global commit          8820d49b18d950f5b125385c4ebfd42c69fd29d4

%gometa -f

%global common_description %{expand:
Go-Attestation abstracts remote attestation operations across a variety of
platforms and TPMs, enabling remote validation of machine identity and state.}

%global golicenses      LICENSE
%global godocs          docs CONTRIBUTING.md README.md attest/attest-\\\
                        tool/README.md

Name:           %{goname}
Release:        %autorelease -p
Summary:        None

License:        Apache-2.0
URL:            %{gourl}
Source:         %{gosource}

BuildRequires:  golang(github.com/google/certificate-transparency-go/asn1)
BuildRequires:  golang(github.com/google/certificate-transparency-go/x509)
BuildRequires:  golang(github.com/google/certificate-transparency-go/x509/pkix)
%if %{without bootstrap}
BuildRequires:  golang(github.com/google/go-tpm/tpm)
BuildRequires:  golang(github.com/google/go-tpm/tpm2)
BuildRequires:  golang(github.com/google/go-tpm/tpm2/credactivation)
BuildRequires:  golang(github.com/google/go-tpm/tpmutil)
%endif
BuildRequires:  golang(github.com/google/go-tspi/verification)

%if %{with check}
# Tests
BuildRequires:  golang(github.com/google/go-cmp/cmp)
BuildRequires:  golang(github.com/google/go-cmp/cmp/cmpopts)
%if %{without bootstrap}
BuildRequires:  golang(github.com/google/go-tpm-tools/simulator)
%endif
%endif

%description %{common_description}

%gopkg

%prep
%goprep

%build
%if %{without bootstrap}
for cmd in attest/attest-tool; do
  %gobuild -o %{gobuilddir}/bin/$(basename $cmd) %{goipath}/$cmd
done
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/
%endif

%if %{with check}
%check
%{?with_bootstrap:rm -r attest}
%gocheck
%endif

%if %{without bootstrap}
%files
%license LICENSE
%doc docs CONTRIBUTING.md README.md attest/attest-tool/README.md
%{_bindir}/attest-tool
%endif

%gopkgfiles

%changelog
%autochangelog
